### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#1]
I know! This shouldn't be an issue. It's the the first and last time, I promise!

**Comment by maleck13** [comment]
@guicassolato should we close this issue now?

**Comment by guicassolato** [comment]
> @guicassolato should we close this issue now?

@maleck13, this started almost as a joke... A tragic/funny one considering it's been 3.5 years and nobody's picked the issue since then 🙂

Obviously our test coverage has improved significantly since then, though with tons of work ahead yet to be completely honest. But let's close the issue.
