### ISSUE TITLE
Filter `Secret` resources watched by Authorino `SecretReconciler`

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#116]
Use https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/predicate to filter the events related to Kubernetes `Secret` resources, watched by `SecretReconciler`, only to resources labelled with the Authorino "managed-by" label:

https://github.com/Kuadrant/authorino/blob/6b44f9552fc97b7836137954fa26c19da71aac0c/main.go#L54

**Comment by eguzki** [comment]
This example used in [kuadrant-controller](https://github.com/Kuadrant/kuadrant-controller) is doing pretty much the same, but with services instead of the secrets.

```go
// SetupWithManager sets up the controller with the Manager.
func (r *ServiceReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		WithEventFilter(onlyLabeledServices()).
		For(&corev1.Service{}).
		Complete(r)
}

func onlyLabeledServices() predicate.Predicate {
	return predicate.Funcs{
		CreateFunc: func(e event.CreateEvent) bool {
			// Lets filter for only Services that have the kuadrant label and are enabled.
			if val, ok := e.Object.GetLabels()[kuadrantDiscoveryLabel]; ok {
				enabled, _ := strconv.ParseBool(val)
				return enabled
			}
			return false
		},
		UpdateFunc: func(e event.UpdateEvent) bool {
			// In case the update object had the kuadrant label set to true, we need to reconcile it.
			if val, ok := e.ObjectOld.GetLabels()[kuadrantDiscoveryLabel]; ok {
				enabled, _ := strconv.ParseBool(val)
				return enabled
			}
			// In case that service gets update by adding the label, and set to true, we need to reconcile it.
			if val, ok := e.ObjectNew.GetLabels()[kuadrantDiscoveryLabel]; ok {
				enabled, _ := strconv.ParseBool(val)
				return enabled
			}

			return false
		},
		DeleteFunc: func(e event.DeleteEvent) bool {
			// If the object had the Kuadrant label, we need to handle its deletion
			_, ok := e.Object.GetLabels()[kuadrantDiscoveryLabel]
			return ok
		},
	}
}
```

Hopefully it is useful.

For the labels, the kuadrant controller needs to implement a custom predicate. The reason is that the controller also wants to catch resources update events when the old object had the expected label, not only the new one. If this is not your case, if on update events only the new object labels need to be matched, there is a helper function for that that does all the glue code of the predicates. Nicer. 
```go
// SetupWithManager sets up the controller with the Manager.
func (r *ServiceReconciler) SetupWithManager(mgr ctrl.Manager) error {                      
    kuadrantServicePredicate, err := predicate.LabelSelectorPredicate(metav1.LabelSelector{ 
        MatchLabels: map[string]string{kuadrantDiscoveryLabel: "true"},                     
    })                                                                                      
    if err != nil {                                                                         
        return err                                                                          
    }                                                                                       
                                                                                            
    return ctrl.NewControllerManagedBy(mgr).                                                
        WithEventFilter(kuadrantServicePredicate).                                          
        For(&corev1.Service{}).                                                             
        Complete(r)                                                                         
}                                                                                           

```

**Comment by jjaferson** [comment]
@eguzki I like the idea of using the `LabelSelectorPredicate` so we don't need to create a custom predicate for it but this predicate is not available on the `controller-runtime` version used by authorino at the moment (https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.6.3/pkg/predicate). 

Maybe we should be looking into updating the `controller-runtime` version as well as the version of the operator-sdk

**Comment by guicassolato** [comment]
> Maybe we should be looking into updating the `controller-runtime` version as well as the version of the operator-sdk

Agreed. See #125.

**Comment by jjaferson** [comment]
> > Maybe we should be looking into updating the `controller-runtime` version as well as the version of the operator-sdk
> 
> Agreed. See #125.

Nice one @guicassolato I might look into getting the `controller-runtime` version upgraded
