### ISSUE TITLE
s/master/main/g

### ISSUE THREAD

**Issue by gsaslis** [Kuadrant/authorino#118]
Is it early enough in the project's lifecycle to rename our main branch?

`main` is now the default branch name on (at least) github, gitlab, etc. so **if nothing else** (despite your views on the main branch naming subject), keeping `master` makes this repo feel "old". 

So, let's move away from `master`!!

**Comment by gsaslis** [comment]
Looking at the github actions, it seems `main` is already supported, so this looks even easier than I thought!

**Comment by guicassolato** [comment]
Done. Thanks, @gsaslis!
