### ISSUE TITLE
Upgrade envtest

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#134]
[controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) introduced a new Envtest setup tool in v0.9.0 (see release note [here](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.9.0)), so Authorino's `make test` should stop downloading `hack/setup-envtest.sh` and switch to `sigs.k8s.io/controller-runtime/tools/setup-envtest`. 

Docs: https://github.com/kubernetes-sigs/controller-runtime/tree/master/tools/setup-envtest

**Comment by jjaferson** [comment]
@guicassolato Do we want to use always the latest version of the setup-envtest or stick to an specific version?

**Comment by guicassolato** [comment]
> @guicassolato Do we want to use always the latest version of the setup-envtest or stick to an specific version?

I think it's ok to install latest, and, in case we need a specific version, we can set it in `setup-envtest use`.
