### ISSUE TITLE
Tracing

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#163]
As part of a chain of requests that by definition includes several other systems and services, the authorization service should have support for request tracing. That includes possibility to track and trace request tokens/IDs throughout the end-to-end steps and hops of the auth pipeline, either a token verification request that relies on an external auth server, ad-hoc auth metadata fetched, etc.

**Comment by Rohith-Raju** [comment]
Hi, I'm new here 😄. Is this issue still relavent?

**Comment by guicassolato** [comment]
Hi @Rohith-Raju. 

> Is this issue still relavent?

It is. Since it was opened, over a year ago, a few things changed; in a way that the issue deserves at least a better scope definition nevertheless.

Starting by what we still miss in Authorino, I'd say: proper embedded telemetry reporting, like by integrating OpenTracing. This is a relatively easy task to implement that could re-shape the description above.

What Authorino can do already, on the other hand, – and I should be more clear about it in the description as well – is:
1. it propagates a `request id` to the logs - this ID is typically generated by the API gateway and retrieved by Authorino (although there is at least one [exception](https://github.com/Kuadrant/authorino/blob/main/docs/architecture.md#raw-http-authorization-interface) where the ID is generated by Authorino itself) and, provided you are exporting the logs to something like CloudWatch, it allows you to trace authorization workloads to the level of linking requests to corresponding responses and original HTTP contexts from the gateway or proxy - doc available [here](https://github.com/Kuadrant/authorino/blob/main/docs/user-guides/observability.md#tracing);
2. with the newly introduced [`notify`](https://github.com/Kuadrant/authorino/blob/main/docs/features.md#notifications-notify) phase of the AuthPipeline (#368, soon to be renamed as `callbacks` by #371), one can "trace" authorization requests by specifying one or more callback configs in the AuthConfig to HTTP endpoints of a tracing system - authentication options between Authorino and this external HTTP server are still limited, but if that's not an issue the requests themselves can contain fairly detailed information, such results of the evaluation of each authorization rule, combined with some user info, etc.

I hope this answers your question.

**Comment by Rohith-Raju** [comment]
Thanks for the info. I'd like to work on this issue.
I'm aware of the working of authorino (by deploying a hello world scenario) also done setting up the project locally.
How do I start working on this issue?

**Comment by guicassolato** [comment]
That's brilliant, @Rohith-Raju! We really appreciate your interest in contributing to Authorino.

There's a [Developer's Guide](https://github.com/Kuadrant/authorino/blob/main/docs/contributing.md) where you'll find a few initial guidelines.

After that, it really depends on how familiar you get with the code base, how much you know about [OpenTelemetry](https://opentelemetry.io/), which I'd recommend as the go-to standard to get this issue done.

Start with something simple, such as instrumenting the `AuthService.Check` function from the `github.com/kuadrant/authorino/pkg/service` package.

Here's a guide to help you get through the first steps: https://opentelemetry.io/docs/instrumentation/go/getting-started. You'll want to focus on the [Trace Instrumentation](https://opentelemetry.io/docs/instrumentation/go/getting-started/#trace-instrumentation) chapter first. Then, instead of following the example of the console exporter, you'd rather favour an external service like Jeager or SigNoz. There are plenty of examples on the web for that too.

In a second iteration, we can try defining related spans for the functions deeper in the stack, such as `AuthPipeline.Evaluate` and so.

There is no rush though. Take your time and reach out as much as you need.

You may want to join us at our Slack channel: [kuadrant.slack.com](https://kuadrant.slack.com/) _#authorino_.

Cheers!

**Comment by Rohith-Raju** [comment]
Thanks for your message @guicassolato I will go through the steps and learn the above-mentioned. I couldn't sign up to slack as there was no option as such. Could you please invite me? my email is  meetrohithkraju@gmail.com 😄
