### ISSUE TITLE
Provide the ability to limit the available features set

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/authorino#227]
As a cluster administrator I would like to control the supported auth mechanisms offered to my developers via Authorino so that I can ensure the applications leveraging Authorino conform to my organisations standards. 

**Describe the solution you'd like**

When installing Authorino I would like to be able to limit the feature set via set of env vars or feature flags. For example, if I wanted to disable the ability to use API Key auth or only allow OIDC

**Describe alternatives you've considered**

None currently.

**Additional context**
Not sure if this should extend to authz as well as authn

**Comment by guicassolato** [comment]
@maleck13, do you see this as a per-instance type of flag, where once a particular Authorino feature is disabled for an instance of Authorino, it is disabled for the entire instance, i.e. no user can "send" AuthConfigs to this instance containing that disabled feature? Or do you see it as something where a feature X of Authorino can be enabled for a group of AuthConfig owners in an Authorino instance and disabled for another group of AuthConfig owners in the same Authorino instance?

<br/>

We have discussed about this RFE in today's weekly update meeting and 2 different approaches were proposed.

**Approach 1.** Breaking down the AuthConfig CRD into multiple smaller CRDs.

Each Authorino feature (e.g. OIDC authn, API key authn, HTTP metadata, OPA authz, JSON pattern-matching authz, Wristband tokens, etc) would be a separate CRD, and the AuthConfig itself would become something just to link a list hosts to series of CR refs, in a particular order.

This approach would allow to enable/disable features of Authorino via Kubernetes RBAC, effectively making possible to achieve feature switches at the level of each AuthConfig owner. On the other hand, it would mean a significant change in the API, one that in itself would justify a major version release IMO.

I also wonder whether attaching a feature switch to individual instances running in a cluster would be possible, or if when a cluster user is not authorised to use a particular feature of Authorino, it is not authorised in the entire cluster, regardless of Authorino instance.

Questions regarding usability in this approach were raised as well. For simple use cases, setting up an AuthConfig with just a couple of Authorino evaluators could become a bit overkill requiring 3 different CRs applied to the cluster. Moreover, we lose readability of the AuthConfig. An obvious solution to that, but that also comes with its very own pickles, would be having a CRD facade that holds the whole thing and it's split up behind the scenes into the smaller bits.

**Approach 2.** Set up flags at the level of the instance (e.g. using env vars).

A ValidatingWebhookConfiguration could be used to reject AuthConfigs that try to use a disabled feature.

This is a lot simpler and I think it goes in the line of what you suggested. The bad thing is that it cannot be controlled for individual AuthConfig owners (or owner groups); if an Authorino feature is disabled in a given Authorino instance, it is disabled for all users of that instance.

It is also less K8s-nativey, although I don't think that's too much of an issue in this case. (I'd state the opposite, if it was for us to follow this approach and yet try to improvise some per-user switch without relying on the K8s RBAC for it.)

Probably a simple config option in the form of a comma-separated list of features to enable/disable (e.g. `disabledFeatures=identity.apiKey,metadata.http,authorization.kubernetes`), set in one env var or command-line arg, would be the way to configure this in the Authorino container (better IMO)... Or we can expect tons of new env vars/command-line args added to the Authorino deployment, which I think it's noisy and harder to maintain.

In the `Authorino` CRD (Authorino Operator), we can have each feature switch as separate field if we want.

<br/>

I think most opinions were leaning towards approach 2 in the call today, with feature switches supported at the level of the Authorino instance only, and no changes in the AuthConfig API.

There was a 3rd idea involving multiple AuthConfig API versions, but that was easily discarded.

<br/>

WDYT of all this? Would you also say approach 2 is what want here?

**Comment by maleck13** [comment]
> do you see this as a per-instance type of flag, where once a particular Authorino feature is disabled for an instance of Authorino, it is disabled for the entire instance, i.e. no user can "send" AuthConfigs to this instance containing that disabled feature? Or do you see it as something where a feature X of Authorino can be enabled for a group of AuthConfig owners in an Authorino instance and disabled for another group of AuthConfig owners in the same Authorino instance?

I had been thinking it is something that an admin would configure for all instances of Authorino on a given cluster.

With option 2 and start up flags, this is a pattern used by the kubernetes APIServer to enable and disable certain features https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/  ``` --disable-admission-plugins strings ```

**Comment by maleck13** [comment]
I like the idea of the validating webhook, rejecting an AuthConfig that uses a feature that is disabled. Need to think about the user experience and ensure it is clear to the end user why there authconfig was rejected
