### ISSUE TITLE
Command-line args instead of env vars

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#363]
Authorino reads configuration for the executable from environment variables. This is not ideal as env vars usually belong to the global state of the operating system and, most importantly, are mutable. We should follow a better practice and read configuration options from command-line arguments instead.

This will require changes in https://github.com/kuadrant/authorino-operator as well.

**Comment by gsaslis** [comment]
@guicassolato this caught my eye - just wondering if this implies that authorino can never pick up configuration changes **at runtime** ? 

i.e. would I always need to restart pods for config changes to be picked up ? are there cases where the application logic would need to handle a certain config param's value **transition** ?

**Comment by guicassolato** [comment]
> just wondering if this implies that authorino can never pick up configuration changes at runtime

@gsaslis, this is true for things as they are today already. Authorino reads env vars at boot-time and then works with those values all along.

So what we gain here with this issue is not really predictability about the execution itself, but rather the ability to read the state of the application as of when it was booted in the first place. By reading the env vars on the other hand, you know the _current_ values, but not the original ones (at least not from within the environment).

One could argue that in a containerised world, env vars are (should be) immutable and you should always redeploy the application when you want to modify the environment, like for example by editing a `Deployment` resource in Kubernetes. However, if that is true, then so is your original statement all the same. Authorino never picks up configuration changes at runtime.

That all been said, a couple things about this issue I did not say before are that it also has to do with:
1. improving the command-line for the application – something we did for Limitador already (https://github.com/Kuadrant/limitador/pull/92);
2. standardising the way boot options are passed to the application – today there's a mix of env vars and command-line args.

As final thoughts, I would add that, for inter-process communication, there are better ways to exchange data than by modifying the global state of environment; while for intra-process using env vars is an indication of bad design IMO.

_All the freedom we deserve, but just as much so we don't hurt ourselves!_ 🙂
