### ISSUE TITLE
Ability to send logs of the authorization response

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#364]
Request for making possible for users to set in the AuthConfig a step to send logs of the authorization result (or arbitrary HTTP requests in general) after the `authorization` phase.

Currently it's only possible to implement something along these lines in OPA and if either the entire authorization is wrapped into one single OPA evaluator (which can harm performance, scalability and maintainability of the authz layer) or by limiting those logs to successful authorization only (which hardly cover the main use case for this: reporting most of all the failure attempts). Either way, technically none of these approaches would be _after_ the `authorization` phase and therefore at least the section corresponding to the `response` phase wouldn't be available in the Authorization JSON.

**Comment by maleck13** [comment]
@guicassolato why would they do it this way and not just export logs from authorino to something like cloud-watch for this use-case? 
Do we know what size payload this might be? How would the logs be gathered to send  is that something Authorino would do? Not against the idea of a post authz webhook, just wondering about this particular use-case.

**Comment by guicassolato** [comment]
> why would they do it this way and not just export logs from authorino to something like cloud-watch for this use-case?

It's a good question, @maleck13. I think it's about having more control over _what_ and _when_ to report. Authorino logs are very conservative, dumping to the logs no much more than "access granted/denied" – no user data, no context info other than a request ID. Then it's up to whoever reads that to (1) filter – because by exporting the logs you actually get a clip of history containing loose messages from multiple unrelated requests – and (2) trace – i.e. link the requests to corresponding responses using the request ID, which in turn is generated in Envoy, that gives you more context.

A way to report when a particular access is denied and for whom, right when it happens, with details of which policy rules succeeded and which ones failed, can be very useful. I think this is the actual use case.

> Do we know what size payload this might be? How would the logs be gathered to send is that something Authorino would do?

With the solution I was envisioning (#368), the user controls the payload; it can be as big as the entire [Authorization JSON](http://kuadrant.io/docs/authorino/architecture.html#the-authorization-json), it can be conditional (e.g. only when access is denied). It would not be based on logs.

As for the exporting the logs alternative, as I said, I don't think that covers the use case.
