### ISSUE TITLE
Propagate traces to external services

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#385]
Make HTTP requests sent by Authorino to external services traceable, by injecting the headers (`traceparent` and `tracestate`, and `baggage`), from the context:
- External sources of metadata
- HTTP callbacks
- OPA policy registries
- etc

Related to #163.

---

Implementation:

```go
otel.GetTextMapPropagator().Inject(ctx, otel_propagation.HeaderCarrier(req.Header()))
```

**Comment by Rohith-Raju** [comment]
Hey, @guicassolato I'd like to go ahead with this

**Comment by guicassolato** [comment]
> Hey, @guicassolato I'd like to go ahead with this

Thank you @Rohith-Raju! We really appreciate your help!
