### ISSUE TITLE
Add commit hash dirty implementation, similar to kuadrantctl, to authorino. 

### ISSUE THREAD

**Issue by ehearneRedHat** [Kuadrant/authorino#471]
After speaking with @eguzki in [kuadrantctl #85](https://github.com/Kuadrant/kuadrantctl/pull/85) , the idea of adding a commit hash to the version output of authorino, similar to kuadrantctl, would be a great way for users to see where exactly their version of authorino is coming from. 

This can be done through a Makefile target, such as in `build` . Refer to the above issue to see how it was implemented in kuadrantctl for context. 

### Additional Context 

In addition to the already implemented version and hash being displayed, it would be great to show whether the version of authorino contains just the work on the main branch, or if there were additional changes made to the repository before being committed. 

Within kuadrantctl, when `./kuadrantctl version` is used, the output when there is additional changes made before being compiled, looks like

` kuadrantctl version: <version> (<git-hash>-dirty) `

A hash, while beneficial to the keen eye, can easily be overlooked, where as by showing the the branch in question has changes unknown to the user, they can go ahead and remove those changes so their binary is not dirty.

Therefore, within authorino, this additional feature, when the branch has new changes, can be implemented something like

```bash
$ ./authorino version
Authorino dc90ac837c3babc6afe6e1e5aacb64fe84c58088 (dirty)
```

Otherwise, it will remain the same if no new changes were made to the branch

```bash
$ ./authorino version
Authorino dc90ac837c3babc6afe6e1e5aacb64fe84c58088
```

**Comment by guicassolato** [comment]
@ehearneRedHat, the Authorino binary already includes the version, which is either a SHA (latest builds) or a semantic version (releases.)

Apart from printed to the logs when the auth server starts:

```
{"level":"info","ts":"2024-06-12T13:48:57Z","logger":"authorino","msg":"booting up authorino","version":"dc90ac837c3babc6afe6e1e5aacb64fe84c58088","cmd":"server"}
```

one can also check it by running:

```
$ ./authorino version
Authorino dc90ac837c3babc6afe6e1e5aacb64fe84c58088
```

**Comment by ehearneRedHat** [comment]
@guicassolato I was speaking with @eguzki again, and I was made aware that additional context may be needed to understand what the proposed feature was. 

I have added that context to the first comment. Thank you for the additional information. :)
