### ISSUE TITLE
Support for Common Expression Language (CEL)

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#475]
Add support for [Common Expression Language (CEL)](https://cel.dev/) as alternative for all selectors currently based on [tidwall/gjson](https://gjson.dev/), including:
- [`NamedPatterns`](https://github.com/Kuadrant/authorino/blob/1ac43d69d75ec1a5f604503994078e2df801dcd8/api/v1beta2/auth_config_types.go#L157)
- [`ValueOrSelector`](https://github.com/Kuadrant/authorino/blob/1ac43d69d75ec1a5f604503994078e2df801dcd8/api/v1beta2/auth_config_types.go#L200) and [`NamedValuesOrSelectors`](https://github.com/Kuadrant/authorino/blob/1ac43d69d75ec1a5f604503994078e2df801dcd8/api/v1beta2/auth_config_types.go#L189C6-L189C28)
- [Plain identity selector](https://github.com/Kuadrant/authorino/blob/main/api/v1beta2/auth_config_types.go#L403)

### CEL as a superset of gjson-powered Authorino features

TBC – All gjson-powered features supported in Authorino can be modeled and supported in CEL. Special attention to be given to gjson's [modifiers](https://github.com/tidwall/gjson?tab=readme-ov-file#modifiers-and-path-chaining) and [custom ones](https://docs.kuadrant.io/0.8.0/authorino/docs/features/#string-modifiers) introduced by Authorino.

### Should CEL paths become the standard?

To keep backward compatibility, maybe the paths specified in CEL can be prefixed with `cel:`, until slowly transitioned to become the default, when either we can drop support to gjson or introduce a prefix for it to keep being supported.

**Comment by alexsnaps** [comment]
wrt modifiers, I think these can be custom functions we add to the cel interpreter. I'd suggest we keep these align across the "runtimes" tho, i.e. have them being kuadrant-wide extensions (wasm-shim, limitador, ...)
