### ISSUE TITLE
First class support for parh based APIs in AuthConfig

### ISSUE THREAD

**Issue by eshepelyuk** [Kuadrant/authorino#486]
Hello

I've created a discussion, https://github.com/Kuadrant/authorino/discussions/485
 but not sure which is more preferrable: issue or discussion.

Plz let me know what should be kept.

**Comment by guicassolato** [comment]
Hello @eshepelyuk!

Discussions are usually better for topics with multiple of ramification (so people can comment on each thread separately). We don't use them a lot in Authorino, but it's really up to you. While issues tend to be more suitable for feature requests, bug reporting and simple questions, I guess.

In this particular case, I left an answer for you in the discussion (which I've already seen you replied to.) Let me try to elaborate on the problem with supporting path-based lookup there. If needed, we can reopen this issue with a more concrete plan.
